services:
  portfolio:
    # Build the image from the Dockerfile in the current directory
    build: .
    env_file: .env
    container_name: portfolio
    command: "uv run src/athrerank run --host ${HOST} --port ${PORT}"
    # Host the FastAPI application on port 8000
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    restart: unless-stopped
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=myresolver"
      - "traefik.http.services.portfolio.loadbalancer.server.port=${PORT}"

networks:
  traefik-network:
    external: true