services:
  web:
    # Build the image from the Dockerfile in the current directory
    build: .
    env_file: .env.production
    command: "python src/athrerank run --host ${HOST} --port ${PORT}"
    # Host the FastAPI application on port 8000
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    restart: unless-stopped
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(${HOST})"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=myresolver"
      - "traefik.http.services.portfolio.loadbalancer.server.port=80"

networks:
  traefik-network:
    external: true