line-length = 100
target-version = "py312"

[lint]
# https://github.com/astral-sh/ruff/discussions/12983
# Ignore this for CLI arguments
ignore = ["COM812"]

[format]
line-ending = "auto"
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false